version: "3.9"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sample
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
#    network_mode: samla
    extra_hosts:
      - "host.docker.internal:172.23.0.1"


  diploma1:
    container_name: diploma1
    image: sha256:a3fde0ddef0780e7b0795cd78caacf1bfac334bcd55b03975992d5075866ef37
    #sha256:99715675bb1551622e6615498d7bdf2e4b2e0c745b66b7698879d187736a6fa9
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
#    network_mode: samla

networks:
  samla:
    external: true