spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/sample
#    url: jdbc:mysql://localhost:3306/sample
    driverClassName: org.postgresql.Driver
    username: postgres
    password: qwerty
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      continue-on-error: true
  graphql:
    graphiql:
      enabled: true
    playground:
      enabled: true

voyager:
  cdn:
    enabled: true
